// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	CHAIN_RPC_MAP: string;
	CHAIN_PRIVATE_RPC_MAP: string;
	ETH_PRIVATE_KEY: `0x${string}`;
	WHITELISTED_ADDRESSES: string;
	MAX_BASE_FEE: string;
	USE_PRIVATE_TRANSACTIONS: string;
	API_SECRETS: string;
	NONCE_KV: KVNamespace;
}
