#:schema node_modules/wrangler/config-schema.json
name = "eth-relay-worker"
main = "src/index.ts"
compatibility_date = "2024-07-01"

[[kv_namespaces]]
binding = "NONCE_KV"
id = "b2f057681bf94689b1b861644924c304"
